"""update tables

Revision ID: c8b8d0f5e0a1
Revises: 0b9f846d88cd
Create Date: 2026-01-26 13:19:33.471369

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'c8b8d0f5e0a1'
down_revision: Union[str, Sequence[str], None] = '0b9f846d88cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # refresh_tokens table
    op.alter_column(
        'refresh_tokens',
        'created_at',
        existing_type=mysql.DATETIME(),
        type_=sa.TIMESTAMP(),
        server_default=sa.text("CURRENT_TIMESTAMP"),
        existing_nullable=False
    )

    # users table
    op.alter_column(
        'users',
        'created_at',
        existing_type=mysql.DATETIME(),
        type_=sa.TIMESTAMP(),
        server_default=sa.text("CURRENT_TIMESTAMP"),
        existing_nullable=False
    )

    op.alter_column(
        'users',
        'updated_at',
        existing_type=mysql.DATETIME(),
        type_=sa.TIMESTAMP(),
        server_default=sa.text("CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP"),
        existing_nullable=False
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'updated_at',
               existing_type=sa.TIMESTAMP(timezone=True),
               type_=mysql.DATETIME(),
               existing_nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=sa.TIMESTAMP(timezone=True),
               type_=mysql.DATETIME(),
               existing_nullable=False)
    op.alter_column('refresh_tokens', 'created_at',
               existing_type=sa.TIMESTAMP(timezone=True),
               type_=mysql.DATETIME(),
               existing_nullable=False)
    op.alter_column('refresh_tokens', 'expires_at',
               existing_type=sa.TIMESTAMP(timezone=True),
               type_=mysql.DATETIME(),
               existing_nullable=False)
    # ### end Alembic commands ###
